### DISCUSSION TITLE
Another thing I seem to need assistance with

### DISCUSSION THREAD

**Discussion by MHFDoge** [FoxxMD/context-mod#144] [Q&A]
Hi again, Currently, part of the config I am using contains rules to check the profile activity of the OP of every post submitted. If activity over a certain window of time contains more than two hits, the post gets reported, and mods can then manually review it. The problem I am running into now because each of those subreddits being looked for has been manually added, is because that config is presently over 600 lines long(>330 of those lines being one per line subreddit entries), and I would like to duplicate those checks to also operate in some capacity on comments. I was wondering if there was a way that I could create a fixed list, be it stored in the same config, or as a separate file, that I can then use in place of a list of subreddits, I would prefer being able to just modify _one_ thing, and have it update accordingly across both checks, as well as prevent this config from reaching 1k lines long faster than it needs to. 

Is this functionality present without having to modify the templating source files? or am I just without many other options here. 
A structure-matching version of one of the rules is as follows:
```yaml

##################################################################################################################
      - name: acct-history
        description: example description.
        # check will run on a new submission in your subreddit and look at the Author of that submission
        kind: submission
        rules:
          - name: accthist
            kind: recentActivity
            # // when lookAt is not present this rule will look for submissions and comments
            #lookAt: comments
            useSubmissionAsReference: false
            thresholds:
              # if the number of activities (sub/comment) found CUMULATIVELY in the subreddits listed is
              # equal to or greater than 2 then the rule is triggered
              - threshold: '>= 2'
                subreddits:
                  - subreddit1
                  - subreddit2
                  #etc etc
            window: 7 days
        actions:
          - kind: report
            content: >-
              {{rules.accthist.totalCount}} activities in flagged subs
              {{rules.accthist.subCount}} subs over {{rules.accthist.window}}:
              {{rules.accthist.subSummary}}
```
