### ISSUE TITLE
bot works, but web interface claims "bot not found"?

### ISSUE THREAD

**Issue by wchristian** [FoxxMD/context-mod#85]
The bot moderates fine as far as i can tell, but in the web interface, when i click on e.g. the config view, i get this:

http://localhost:8085/config?format=yaml&instance=&bot=VaushVall&subreddit=r/VaushV

![image](https://user-images.githubusercontent.com/175467/161544309-1d63bb17-d3b1-4360-9781-923cbb1e9ac6.png)

The docker log shows nothing. Where do i even start debugging this?

**Comment by FoxxMD** [comment]
For fetching/saving the configuration CM uses auth from the account you used to login to the dashboard with. Meaning, the reddit account you logged in with must be able to access/edit the wiki page for the subreddit you are viewing IE `r/VaushV`

Can you confirm that your account has `full` mod permissions or at least `manage wiki` mod permission for `r/VaushV` ?

**Comment by wchristian** [comment]
Ah, sorry, i was unclear, that happens in a lot of places in the ui. The frontpage debug log is loaded the first time, but the spinner goes endlessly and the network tab of chrome says there's a 404 XHR call.
![image](https://user-images.githubusercontent.com/175467/161573893-e94956b7-3b50-4c2b-b0dc-438b579a81e7.png)

**Comment by wchristian** [comment]
Also the config looks like this, and i'm logged into the browser with VaushVall, and the permissions look like this.

```yaml
operator:
  name: VaushVall
bots:
  - name: VaushVall
    credentials:
      reddit:
        accessToken: CCCCCCCCCCCCCCCCCC
        refreshToken: DDDDDDDDDDDDDDDDDDDDDDDDDDD
        clientId: AAAAAAAAAAAAAAAAAA
        clientSecret: BBBBBBBBBBBBBBBBBBBBB
    subreddits:
      names:
        - vaushv
web:
  credentials:
    clientId: AAAAAAAAAAAAAAAAAA
    clientSecret: BBBBBBBBBBBBBBBBBBBBB
```

![image](https://user-images.githubusercontent.com/175467/161574329-3a9264a5-4449-462a-9edd-ebc220f295bd.png)

**Comment by FoxxMD** [comment]
I have a hunch this has to do with session persistence. You have not set `caching` in your operator config, correct?

Can you try this:

1. In your operator config under **web** add a session secret like this:

```yaml
web:
  credentials:
   ...
  session:
    secret: mySecret
```

2. Clear cookies/session in your browser ([chrome](https://support.google.com/chrome/answer/95647?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Cdelete-cookies-from-a-site) / [firefox](https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox#w_clear-cookies-for-the-current-website))

3. Restart CM and see if the problem persists
